import { useState } from "react";
import { useLiveQuery } from "dexie-react-hooks";
import { AlertTriangle, ArrowLeft, CheckCircle2, DatabaseBackup, Download, FileSpreadsheet, History, Upload } from "lucide-react";
import { db } from "../db";
import { analyzeBackup, backupFilename, createBackup, parseBackupText, restoreBackup } from "../importExport/backup";
import { exportSessionsCsv, importCsvPreview, previewCsv } from "../importExport/csv";
import { chooseTextFile, saveTextFile } from "../importExport/files";
import type { BackupAnalysis, ConflictPolicy, CsvMapping, CsvPreview, ImportSummary, RestoreMode } from "../importExport/types";

type PreviewState = { kind:"json";analysis:BackupAnalysis;name:string } | { kind:"csv";preview:CsvPreview;text:string;name:string };
const emptySummary:ImportSummary={academicYearsCreated:0,subjectsCreated:0,sessionsImported:0,duplicatesSkipped:0,conflicts:0,invalidRowsSkipped:0};
const activeTimer=()=>{try{const timer=JSON.parse(localStorage.getItem("focus.activeTimer")??"null");return Boolean(timer?.running||timer?.paused||(timer?.sessionId&&timer?.startedAt));}catch{return false;}};

export function ImportExportPage({onNavigate}:{onNavigate:(page:string)=>void}){
  const years=useLiveQuery(()=>db.academicYears.toArray(),[])??[];
  const [preview,setPreview]=useState<PreviewState>(); const [result,setResult]=useState<ImportSummary>(); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const [mode,setMode]=useState<RestoreMode>("merge"); const [policy,setPolicy]=useState<ConflictPolicy>("keep-existing"); const [destinationYear,setDestinationYear]=useState("");
  const exportJson=async()=>{setBusy(true);setError("");try{const backup=await createBackup();if(await saveTextFile(backupFilename(),JSON.stringify(backup,null,2),"json"))await db.settings.put({key:"lastBackupAt",value:new Date().toISOString()});}catch(e){setError(e instanceof Error?e.message:"Backup failed.");}finally{setBusy(false);}};
  const exportCsv=async()=>{setBusy(true);setError("");try{const sessions=await db.sessions.orderBy("startTime").toArray();const date=backupFilename().replace("focus-backup-","").replace(".json","");await saveTextFile(`focus-sessions-${date}.csv`,exportSessionsCsv(sessions),"csv");}catch(e){setError(e instanceof Error?e.message:"CSV export failed.");}finally{setBusy(false);}};
  const inspect=async(file:{name:string;text:string})=>{setError("");setResult(undefined);try{if(!/\.(json|csv)$/i.test(file.name))throw new Error("Choose a .json or .csv file.");if(/\.json$/i.test(file.name)){const backup=parseBackupText(file.text);setPreview({kind:"json",analysis:await analyzeBackup(backup),name:file.name});}else setPreview({kind:"csv",preview:await previewCsv(file.text,undefined,destinationYear||undefined),text:file.text,name:file.name});}catch(e){setPreview(undefined);setError(e instanceof Error?e.message:"The file could not be read.");}};
  const choose=async()=>{const file=await chooseTextFile();if(file)await inspect(file);};
  const remap=async(mapping:CsvMapping,destination=destinationYear)=>{if(preview?.kind!=="csv")return;setDestinationYear(destination);setPreview({...preview,preview:await previewCsv(preview.text,mapping,destination||undefined)});};
  const apply=async()=>{if(!preview)return;if(activeTimer()){setError("Finish or stop the current timer before importing app data.");return;}if(preview.kind==="json"&&mode==="replace"&&!confirm("Replace all persistent Focus data with this backup? This cannot be undone."))return;setBusy(true);setError("");try{const summary=preview.kind==="json"?await restoreBackup(preview.analysis.backup,mode,policy):await importCsvPreview(preview.preview);setResult({...emptySummary,...summary});setPreview(undefined);}catch(e){setError(e instanceof Error?e.message:"Import failed. No partial changes were kept.");}finally{setBusy(false);}};
  if(result)return <main className="page import-page"><header className="page-header"><div><h1>Import complete</h1><p>Your Focus data was updated in one transaction.</p></div></header><section className="result-panel"><CheckCircle2/><div className="result-grid"><span>Academic Years created<strong>{result.academicYearsCreated}</strong></span><span>Subjects created<strong>{result.subjectsCreated}</strong></span><span>Sessions imported<strong>{result.sessionsImported}</strong></span><span>Duplicates skipped<strong>{result.duplicatesSkipped}</strong></span><span>Invalid rows skipped<strong>{result.invalidRowsSkipped}</strong></span><span>Conflicts<strong>{result.conflicts}</strong></span></div><div className="import-actions"><button onClick={()=>setResult(undefined)}><ArrowLeft/> Import / Export</button><button className="primary-action" onClick={()=>onNavigate("History")}><History/> View History</button></div></section></main>;
  if(preview)return <main className="page import-page"><header className="page-header"><div><h1>Review import</h1><p>{preview.name}</p></div><button className="secondary-action" onClick={()=>setPreview(undefined)}><ArrowLeft/> Choose another file</button></header>{preview.kind==="json"?<JsonPreview analysis={preview.analysis} mode={mode} setMode={setMode} policy={policy} setPolicy={setPolicy}/>:<CsvPreviewPanel data={preview.preview} years={years} destinationYear={destinationYear} onDestination={(id)=>remap(preview.preview.mapping,id)} onMapping={(field,column)=>remap({...preview.preview.mapping,[field]:column||undefined})}/>} {error&&<div className="notice notice--error"><AlertTriangle/>{error}</div>}<div className="confirm-bar"><span>Nothing changes until you confirm.</span><button className="primary-action" disabled={busy} onClick={apply}>{busy?"Importing...":"Confirm import"}</button></div></main>;
  return <main className="page import-page" onDragOver={(e)=>e.preventDefault()} onDrop={(e)=>{e.preventDefault();const file=e.dataTransfer.files[0];if(file)void file.text().then((text)=>inspect({name:file.name,text}));}}><header className="page-header"><div><h1>Import / Export</h1><p>Back up your data or import data from another source.</p></div></header>{error&&<div className="notice notice--error"><AlertTriangle/>{error}</div>}<div className="transfer-grid"><section className="transfer-section"><h2>Export</h2><article className="transfer-item"><DatabaseBackup/><div><h3>Full Backup (JSON)</h3><p>Complete backup of Academic Years, Subjects, Sessions, and Settings.</p></div><button className="primary-action" disabled={busy} onClick={exportJson}><Download/> Export backup</button></article><article className="transfer-item"><FileSpreadsheet/><div><h3>Sessions (CSV)</h3><p>Spreadsheet-friendly complete Session history for Excel and similar tools.</p></div><button className="secondary-action" disabled={busy} onClick={exportCsv}><Download/> Export CSV</button></article></section><section className="transfer-section"><h2>Import</h2><div className="drop-zone"><Upload/><h3>Import Data</h3><p>Restore a Focus backup or import Session records from CSV.</p><button className="secondary-action" disabled={busy} onClick={choose}>Choose file</button><small>or drop a .json or .csv file here</small></div></section></div><div className="storage-note">Your data stays on this device. Export backups regularly.</div></main>;
}

function JsonPreview({analysis,mode,setMode,policy,setPolicy}:{analysis:BackupAnalysis;mode:RestoreMode;setMode:(v:RestoreMode)=>void;policy:ConflictPolicy;setPolicy:(v:ConflictPolicy)=>void}){const b=analysis.backup;return <div className="preview-layout"><section className="preview-panel"><h2>Focus backup</h2><p>Created {new Date(b.exportedAt).toLocaleString()}</p><div className="preview-counts"><span>Academic Years<strong>{b.data.academicYears.length}</strong></span><span>Subjects<strong>{b.data.subjects.length}</strong></span><span>Sessions<strong>{b.data.sessions.length}</strong></span><span>Settings<strong>{b.data.settings.length}</strong></span></div><div className="validation-summary"><CheckCircle2/> Backup structure and references are valid.</div></section><section className="preview-panel"><h2>Restore mode</h2><label className="choice"><input type="radio" checked={mode==="merge"} onChange={()=>setMode("merge")}/><span><strong>Merge with existing data</strong><small>Add missing records and preserve existing data.</small></span></label><label className="choice choice--danger"><input type="radio" checked={mode==="replace"} onChange={()=>setMode("replace")}/><span><strong>Replace existing data</strong><small>Remove persistent local data and restore this backup.</small></span></label>{analysis.conflicts>0&&mode==="merge"&&<><h3>{analysis.conflicts} conflicts found</h3><label className="choice"><input type="radio" checked={policy==="keep-existing"} onChange={()=>setPolicy("keep-existing")}/> Keep existing records</label><label className="choice"><input type="radio" checked={policy==="use-imported"} onChange={()=>setPolicy("use-imported")}/> Use imported records</label></>}<p className="muted">{analysis.duplicates} identical records will be skipped.</p></section></div>}

const fields:[keyof CsvMapping,string][]=[["academicYear","Academic Year"],["subject","Subject"],["startDate","Start Date"],["startTime","Start Time"],["endDate","End Date"],["endTime","End Time"],["startDateTime","Start datetime"],["endDateTime","End datetime"],["focusedMinutes","Duration / Focused Minutes"],["note","Note"],["archived","Archived"]];
function CsvPreviewPanel({data,years,destinationYear,onDestination,onMapping}:{data:CsvPreview;years:{id:string;name:string}[];destinationYear:string;onDestination:(id:string)=>void;onMapping:(field:keyof CsvMapping,column:string)=>void}){const valid=data.rows.filter((r)=>r.session&&!r.errors.length&&!r.duplicate).length,duplicates=data.rows.filter((r)=>r.duplicate).length,invalid=data.rows.filter((r)=>r.errors.length).length;return <div className="preview-layout preview-layout--csv"><section className="preview-panel"><h2>{data.recognizedFocusCsv?"Focus Sessions CSV":"Map CSV columns"}</h2>{!data.recognizedFocusCsv&&<div className="mapping-grid">{fields.map(([field,label])=><label key={field}>{label}<select value={data.mapping[field]??""} onChange={(e)=>onMapping(field,e.target.value)}><option value="">Not mapped</option>{data.headers.map((h)=><option key={h}>{h}</option>)}</select></label>)}</div>}{!data.mapping.academicYear&&<label className="destination-year">Destination Academic Year<select value={destinationYear} onChange={(e)=>onDestination(e.target.value)}><option value="">Select an Academic Year</option>{years.map((y)=><option key={y.id} value={y.id}>{y.name}</option>)}</select></label>}<div className="preview-counts"><span>Valid rows<strong>{valid}</strong></span><span>Duplicates<strong>{duplicates}</strong></span><span>Invalid rows<strong>{invalid}</strong></span><span>New Subjects<strong>{data.subjectsToCreate.length}</strong></span></div>{data.academicYearsToCreate.length>0&&<p className="muted">New Academic Years: {data.academicYearsToCreate.join(", ")}</p>}{data.subjectsToCreate.length>0&&<p className="muted">New Subjects: {data.subjectsToCreate.slice(0,5).map((s)=>`${s.academicYearName} / ${s.subjectName}`).join(", ")}</p>}</section><section className="preview-panel"><h2>First rows</h2><div className="csv-row-list">{data.rows.slice(0,8).map((row)=><div key={row.rowNumber} className={row.errors.length?"invalid":""}><strong>Row {row.rowNumber}</strong><span>{row.subjectName||"No Subject"} · {row.academicYearName||"No Academic Year"}</span><small>{row.duplicate?"Probable duplicate - skipped":row.errors.join(" ")||"Ready to import"}</small></div>)}</div></section></div>}
