import { useMemo, useState } from "react";
import { useLiveQuery } from "dexie-react-hooks";
import { Archive, CalendarDays, Check, MoreHorizontal, Pencil, Plus, RotateCcw, Trash2 } from "lucide-react";
import { db } from "../db";
import { createSession, CURRENT_YEAR_KEY, formatDuration, makeId, setCurrentAcademicYear } from "../data";
import type { AcademicYear, FocusSession, Subject } from "../types";

const COLORS = ["#4da3ff", "#ff4d57", "#ffad3b", "#4dd39a", "#a879ff", "#ff7eb6"];
const dateText = (value?: string) => value ? new Date(`${value}T00:00:00`).toLocaleDateString(undefined, { day: "numeric", month: "short", year: "numeric" }) : "No dates set";

function PageHeader({ title, subtitle, action }: { title: string; subtitle: string; action?: React.ReactNode }) {
  return <header className="page-header"><div><h1>{title}</h1><p>{subtitle}</p></div>{action}</header>;
}

function Modal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) {
  return <div className="modal-backdrop" onMouseDown={onClose}><section className="modal" onMouseDown={(e) => e.stopPropagation()}><h2>{title}</h2>{children}</section></div>;
}

export function AcademicYearsPage() {
  const years = useLiveQuery(() => db.academicYears.orderBy("name").toArray(), []) ?? [];
  const currentId = useLiveQuery(async () => (await db.settings.get(CURRENT_YEAR_KEY))?.value ?? "", []) ?? "";
  const subjects = useLiveQuery(() => db.subjects.toArray(), []) ?? [];
  const sessions = useLiveQuery(() => db.sessions.toArray(), []) ?? [];
  const [archived, setArchived] = useState(false);
  const [editing, setEditing] = useState<AcademicYear | null | undefined>();
  const save = async (form: FormData) => {
    const name = String(form.get("name") ?? "").trim();
    if (!name) return;
    const year: AcademicYear = { id: editing?.id ?? makeId(), name, startDate: String(form.get("startDate") || "") || undefined, endDate: String(form.get("endDate") || "") || undefined, archived: editing?.archived ?? false };
    await db.academicYears.put(year);
    if (!currentId && !year.archived) await setCurrentAcademicYear(year.id);
    setEditing(undefined);
  };
  return <main className="page"><PageHeader title="Academic Years" subtitle="Organise subjects without forcing calendar ranges to be exclusive." action={<button className="primary-action" onClick={() => setEditing(null)}><Plus size={17}/> Add Academic Year</button>}/>
    <div className="tabs"><button className={!archived ? "active" : ""} onClick={() => setArchived(false)}>Active</button><button className={archived ? "active" : ""} onClick={() => setArchived(true)}>Archived</button></div>
    <div className="data-list">{years.filter((y) => y.archived === archived).map((year) => { const yearSubjects = subjects.filter((s) => s.academicYearId === year.id); const ids = new Set(yearSubjects.map((s) => s.id)); const total = sessions.filter((s) => ids.has(s.subjectId) && !s.archived).reduce((n, s) => n + s.focusedDurationSeconds, 0); return <article className="data-row" key={year.id}><CalendarDays/><div className="row-main"><strong>{year.name} {currentId === year.id && <span className="badge">Current</span>}</strong><span>{year.startDate ? `${dateText(year.startDate)} - ${dateText(year.endDate)}` : "Flexible dates"}</span><small>{yearSubjects.length} subjects · {formatDuration(total)}</small></div><div className="row-actions"><button title="Edit" onClick={() => setEditing(year)}><Pencil/></button>{!year.archived && currentId !== year.id && <button title="Set current" onClick={() => setCurrentAcademicYear(year.id)}><Check/></button>}<button title={year.archived ? "Restore" : "Archive"} onClick={async () => { if (!year.archived && currentId === year.id) return alert("Choose another current Academic Year before archiving this one."); await db.academicYears.update(year.id, { archived: !year.archived }); }}>{year.archived ? <RotateCcw/> : <Archive/>}</button></div></article>; })}</div>
    {!years.some((y) => y.archived === archived) && <div className="empty-state"><h2>{archived ? "No archived Academic Years" : "Create your first Academic Year"}</h2><p>{archived ? "Archived Academic Years will remain available here." : "Add a year, course period, or Independent Study."}</p></div>}
    {editing !== undefined && <Modal title={editing ? "Edit Academic Year" : "New Academic Year"} onClose={() => setEditing(undefined)}><form action={save} className="form"><label>Name<input name="name" defaultValue={editing?.name} required autoFocus/></label><div className="form-grid"><label>Start date<input type="date" name="startDate" defaultValue={editing?.startDate}/></label><label>End date<input type="date" name="endDate" defaultValue={editing?.endDate}/></label></div><div className="modal-actions"><button type="button" onClick={() => setEditing(undefined)}>Cancel</button><button className="primary-action">Save</button></div></form></Modal>}
  </main>;
}

export function SubjectsPage() {
  const years = useLiveQuery(() => db.academicYears.toArray(), []) ?? [];
  const subjects = useLiveQuery(() => db.subjects.orderBy("name").toArray(), []) ?? [];
  const sessions = useLiveQuery(() => db.sessions.toArray(), []) ?? [];
  const currentId = useLiveQuery(async () => (await db.settings.get(CURRENT_YEAR_KEY))?.value ?? "", []) ?? "";
  const [yearId, setYearId] = useState("current"); const [archived, setArchived] = useState(false); const [editing, setEditing] = useState<Subject | null | undefined>();
  const selectedYear = yearId === "current" ? currentId : yearId;
  const save = async (form: FormData) => { const name = String(form.get("name") ?? "").trim(); const academicYearId = String(form.get("year")); if (!name || !academicYearId) return; await db.subjects.put({ id: editing?.id ?? makeId(), academicYearId, name, color: editing?.color ?? COLORS[subjects.length % COLORS.length], archived: editing?.archived ?? false }); setEditing(undefined); };
  const visible = subjects.filter((s) => s.archived === archived && (selectedYear === "all" || !selectedYear || s.academicYearId === selectedYear));
  const subjectIsRunning = (id: string) => { try { const timer = JSON.parse(localStorage.getItem("focus.activeTimer") ?? "null"); return Boolean(timer?.running && timer?.subjectId === id); } catch { return false; } };
  return <main className="page"><PageHeader title="Subjects" subtitle="Manage lightweight subjects within each Academic Year." action={<button className="primary-action" disabled={!years.some((y) => !y.archived)} onClick={() => setEditing(null)}><Plus/> Add Subject</button>}/><div className="filter-bar"><label>Academic Year<select value={yearId} onChange={(e) => setYearId(e.target.value)}><option value="current">Current Academic Year</option><option value="all">All Academic Years</option>{years.map((y) => <option key={y.id} value={y.id}>{y.name}{y.id === currentId ? " (Current)" : ""}</option>)}</select></label></div><div className="tabs"><button className={!archived ? "active" : ""} onClick={() => setArchived(false)}>Active</button><button className={archived ? "active" : ""} onClick={() => setArchived(true)}>Archived</button></div><div className="data-list">{visible.map((subject) => { const used = sessions.filter((s) => s.subjectId === subject.id); const total = used.reduce((n,s) => n + s.focusedDurationSeconds,0); const running = subjectIsRunning(subject.id); return <article className="data-row" key={subject.id}><span className="list-dot" style={{background:subject.color}}/><div className="row-main"><strong>{subject.name}</strong><span>{years.find((y) => y.id === subject.academicYearId)?.name ?? "Unknown Academic Year"}</span><small>{used.length} sessions · {formatDuration(total)}</small></div><div className="row-actions"><button title="Edit" onClick={() => setEditing(subject)}><Pencil/></button><button disabled={running} title={running ? "Stop the active timer first" : subject.archived ? "Restore" : "Archive"} onClick={() => db.subjects.update(subject.id,{archived:!subject.archived})}>{subject.archived ? <RotateCcw/>:<Archive/>}</button>{used.length === 0 && <button disabled={running} title={running ? "Stop the active timer first" : "Delete unused subject"} onClick={() => confirm(`Delete ${subject.name}?`) && db.subjects.delete(subject.id)}><Trash2/></button>}</div></article>;})}</div>{!visible.length && <div className="empty-state"><h2>{archived ? "No archived Subjects" : "Add a Subject to start tracking focus time"}</h2></div>}
    {editing !== undefined && <Modal title={editing ? "Edit Subject":"New Subject"} onClose={() => setEditing(undefined)}><form action={save} className="form"><label>Name<input name="name" defaultValue={editing?.name} required autoFocus/></label><label>Academic Year<select name="year" defaultValue={editing?.academicYearId || currentId} required>{years.filter((y) => !y.archived || y.id === editing?.academicYearId).map((y)=><option key={y.id} value={y.id}>{y.name}</option>)}</select></label><div className="modal-actions"><button type="button" onClick={() => setEditing(undefined)}>Cancel</button><button className="primary-action">Save</button></div></form></Modal>}
  </main>;
}

export function HistoryPage() {
  const years = useLiveQuery(() => db.academicYears.toArray(), []) ?? []; const subjects = useLiveQuery(() => db.subjects.toArray(), []) ?? [];
  const sessions = useLiveQuery(() => db.sessions.orderBy("startTime").reverse().toArray(), []) ?? [];
  const [status,setStatus]=useState("active"); const [yearId,setYearId]=useState(""); const [subjectId,setSubjectId]=useState(""); const [page,setPage]=useState(0); const [editing,setEditing]=useState<FocusSession|null|undefined>(); const pageSize=20;
  const filtered=useMemo(()=>sessions.filter((s)=>(status==="all"||s.archived===(status==="archived"))&&(!yearId||s.academicYearId===yearId)&&(!subjectId||s.subjectId===subjectId)),[sessions,status,yearId,subjectId]);
  const save=async(form:FormData)=>{const subject=subjects.find((s)=>s.id===String(form.get("subject"))); const year=years.find((y)=>y.id===subject?.academicYearId); if(!subject||!year)return; const date=String(form.get("date")),start=String(form.get("start")),end=String(form.get("end")); const startTime=new Date(`${date}T${start}`).getTime(),endTime=new Date(`${date}T${end}`).getTime(); try { if(editing){await db.sessions.update(editing.id,{subjectId:subject.id,subjectName:subject.name,academicYearId:year.id,academicYearName:year.name,startTime,endTime,focusedDurationSeconds:Math.round((endTime-startTime)/1000)});}else await createSession({subject,academicYear:year,startTime,endTime}); setEditing(undefined);}catch(error){alert(error instanceof Error?error.message:"Invalid session");}};
  return <main className="page"><PageHeader title="History" subtitle="Review and correct completed focus sessions." action={<button className="primary-action" disabled={!subjects.length} onClick={()=>setEditing(null)}><Plus/> Add Session</button>}/><div className="filter-bar history-filters"><label>Academic Year<select value={yearId} onChange={(e)=>{setYearId(e.target.value);setPage(0)}}><option value="">All Academic Years</option>{years.map((y)=><option key={y.id} value={y.id}>{y.name}</option>)}</select></label><label>Subject<select value={subjectId} onChange={(e)=>{setSubjectId(e.target.value);setPage(0)}}><option value="">All Subjects</option>{subjects.filter((s)=>!yearId||s.academicYearId===yearId).map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Status<select value={status} onChange={(e)=>{setStatus(e.target.value);setPage(0)}}><option value="active">Active</option><option value="archived">Archived</option><option value="all">All</option></select></label></div><div className="history-table"><div className="history-head"><span>Date</span><span>Time</span><span>Duration</span><span>Subject</span><span>Academic Year</span><span>Status</span><span/></div>{filtered.slice(page*pageSize,(page+1)*pageSize).map((s)=><div className="history-row" key={s.id}><span>{new Date(s.startTime).toLocaleDateString(undefined,{day:"numeric",month:"short",year:"numeric"})}</span><span>{new Date(s.startTime).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})} - {new Date(s.endTime).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</span><strong>{formatDuration(s.focusedDurationSeconds)}</strong><span>{s.subjectName}</span><span>{s.academicYearName}</span><span className="badge">{s.archived?"Archived":"Active"}</span><div className="row-actions"><button title="Edit" onClick={()=>setEditing(s)}><Pencil/></button><button title={s.archived?"Restore":"Archive"} onClick={()=>db.sessions.update(s.id,{archived:!s.archived})}>{s.archived?<RotateCcw/>:<Archive/>}</button>{s.archived&&<button title="Delete permanently" onClick={()=>confirm("Permanently delete this session?")&&db.sessions.delete(s.id)}><Trash2/></button>}</div></div>)}</div>{!filtered.length&&<div className="empty-state"><h2>{status==="archived"?"No archived sessions":"Completed focus sessions will appear here"}</h2></div>}<div className="pagination"><button disabled={!page} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page+1} of {Math.max(1,Math.ceil(filtered.length/pageSize))}</span><button disabled={(page+1)*pageSize>=filtered.length} onClick={()=>setPage(page+1)}>Next</button></div>
    {editing!==undefined&&<Modal title={editing?"Edit Session":"Add Session"} onClose={()=>setEditing(undefined)}><form action={save} className="form"><label>Subject<select name="subject" defaultValue={editing?.subjectId} required>{subjects.filter((s)=>!s.archived||s.id===editing?.subjectId).map((s)=><option key={s.id} value={s.id}>{s.name} · {years.find((y)=>y.id===s.academicYearId)?.name}</option>)}</select></label><label>Date<input type="date" name="date" required defaultValue={new Date(editing?.startTime??Date.now()).toISOString().slice(0,10)}/></label><div className="form-grid"><label>Start<input type="time" name="start" required defaultValue={editing?new Date(editing.startTime).toTimeString().slice(0,5):"09:00"}/></label><label>End<input type="time" name="end" required defaultValue={editing?new Date(editing.endTime).toTimeString().slice(0,5):"10:00"}/></label></div><div className="modal-actions"><button type="button" onClick={()=>setEditing(undefined)}>Cancel</button><button className="primary-action">Save</button></div></form></Modal>}
  </main>;
}
